pychart/pychart/urls.py
"""The URLs for pychart."""

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from pychart.views import HomeView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^login/$', auth_views.login, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^profile/', include('pychart_profile.urls')),
    url(r'^data/', include('pychart_datarender.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pychart/pychart_profile/urls.py
"""URLs for the imager_profile app."""

from django.conf.urls import url

from . import views

app_name = 'pychart_profile'

urlpatterns = [
    url(r'^$', views.ProfileView.as_view(), name="profile"),
    url(r'^edit/$', views.EditProfileView.as_view(), name="edit_profile"),
    url(r'^(?P<username>[\w.@+-]+)/$', views.UserProfileView.as_view(), name="user_profile"),
]

pychart/pychart_profile/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class PyChartProfile(models.Model):
    """Define a Pychart Profile."""

    user = models.OneToOneField(
        User,
        related_name="profile",
        on_delete=models.CASCADE
    )

    objects = models.Manager()

    def __str__(self):
        """Return string representation of profile."""
        return self.user.username


@receiver(post_save, sender=User)
def make_profile(sender, instance, **kwargs):
    """Make a new profile for a new user after new user is saved."""
    if kwargs["created"]:
        new_profile = PyChartProfile(user=instance)
        new_profile.save()

pychart/pychart_profile/forms.py
"""Form module."""

from django import forms
from pychart_profile.models import PyChartProfile


class UserProfileForm(forms.ModelForm):
    """Update form for user profile.

    Thanks, Claire and http://stackoverflow.com/questions/15889794/creating-one-django-form-to-save-two-models
    """

    def __init__(self, *args, **kwargs):
        """Setup the form fields to include User properties."""
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields["First Name"] = forms.CharField(
            initial=self.instance.user.first_name)
        self.fields["Last Name"] = forms.CharField(
            initial=self.instance.user.last_name)
        self.fields["Email"] = forms.EmailField(
            initial=self.instance.user.email)
        del self.fields["user"]

    class Meta:
        """Model for form and fields to exclude."""

        model = PyChartProfile
        exclude = []

pychart/pychart_profile/views.py
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView
from django.views.generic.edit import UpdateView
from pychart_profile.models import PyChartProfile
from pychart_profile.forms import UserProfileForm


class ProfileView(LoginRequiredMixin, DetailView):
    """Display current user's profile."""

    template_name = "pychart_profile/profile.html"
    model = PyChartProfile
    login_url = reverse_lazy("login")

    def get(self, request, *args, **kwargs):
        """Get object from request rather than pk or slug."""
        user = request.user
        return self.render_to_response({'user': user})


class UserProfileView(DetailView):
    """Display any user's profile."""

    template_name = "pychart_profile/user_profile.html"
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    context_object_name = "user"


class EditProfileView(LoginRequiredMixin, UpdateView):
    """Allow user to edit own profile details."""

    login_url = reverse_lazy("login")
    template_name = "pychart_profile/edit_profile.html"
    model = PyChartProfile
    form_class = UserProfileForm

    def get_object(self):
        """Modify get_object to return this user."""
        return PyChartProfile.objects.all().get(user=self.request.user)

    def form_valid(self, form):
        """Save object after post."""
        self.object = form.save()
        self.object.user.first_name = form.cleaned_data['First Name']
        self.object.user.last_name = form.cleaned_data['Last Name']
        self.object.user.email = form.cleaned_data['Email']
        self.object.user.save()
        self.object.save()
        return redirect('/profile')

pychart/pychart_profile/templates/pychart_profile/add_data.html
{% extends "base.html" %}

{% block body %}
<ul>
    <h3>Add Data</h3>

    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
</ul>
{% endblock %}

pychart/pychart_profile/templates/pychart_profile/edit_profile.html
{% extends 'pychart/base.html' %}
{% block content %}
    <h3> Editing {{user.username}}'s Profile </h3>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit Profile">
    </form>

{% endblock %}

pychart/pychart_profile/templates/pychart_profile/profile.html
{% extends 'pychart/base.html' %}
{% block content %}
    <h3>{{user.username}}'s Profile Page</h3>
    <p>Email: {{user.email}}</p>
    <p>First Name: {{user.first_name}}</p>
    <p>Last Name: {{user.last_name}}</p>
    <h5>Profile Options</h5>
    <h6>
        <a href="{% url 'pychart_profile:edit_profile' %}">Edit Profile</a>
    </h6>
{% endblock %}

pychart/pychart_profile/templates/pychart_profile/user_profile.html
{% extends 'pychart/base.html' %}
{% block content %}
    <h3>{{user.username}}'s Profile Page</h3>
    <p>Email: {{user.email}}</p>
    <p>First Name: {{user.first_name}}</p>
    <p>Last Name: {{user.last_name}}</p>
{% endblock %}