pychart/pychart/urls.py
"""The URLs for pychart."""

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from pychart.views import HomeView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^login/$', auth_views.login, name="login"),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^profile/', include('pychart_profile.urls')),
    url(r'^data/', include('pychart_datarender.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pychart/pychart_profile/urls.py
"""URLs for the imager_profile app."""

from django.conf.urls import url

from . import views

app_name = 'pychart_profile'

urlpatterns = [
    url(r'^$', views.ProfileView.as_view(), name="profile"),
    url(r'^edit/$', views.EditProfileView.as_view(), name="edit_profile"),
    url(r'^(?P<username>[\w.@+-]+)/$', views.UserProfileView.as_view(), name="user_profile"),
]

pychart/pychart/views.py
"""This is the pychart views file."""
from django.views.generic import TemplateView
from pychart_datarender.models import Render


class HomeView(TemplateView):
    """Class based view for Home Page."""

    template_name = "pychart/home.html"

    def get_context_data(self):
        """Filter db for a random render for home page."""
        import random
        all_renders = Render.objects.all()

        try:
            random_render = random.choice(all_renders)
        except IndexError:
            random_render = None

        return {'chart': random_render}

pychart/pychart/templates/pychart/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}

    {% endblock %}
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.css">
    <link rel="icon" type="image/x-icon" href="{% static 'imgs/pychart_fav.png' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div>
          <a href="{% url 'home' %}">
            <img class="navbar-btn" src="{% static 'imgs/pychart_nav_logo.png' %}">
          </a>
          </div>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
                <li><a href="{% url 'home' %}">PyChart</a></li>
            {% if not user.is_authenticated %}
                <li><a href="{% url 'registration_register' %}">Register</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
            {% else %}
                <li><a href="{% url 'pychart_profile:profile' %}">Profile</a></li>
                <li><a href="{% url 'gallery' %}">Gallery</a></li>
                <li><a href="{% url 'data_library_view' %}">Data Library</a></li>
                <li><a href="{% url 'data_add' %}">Add Data</a></li>
                <li><a href="{% url 'render_add' %}">Add a Chart</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container main">
      {% block content %}
      {% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/bootstrap-table.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.11.0/locale/bootstrap-table-en-US.min.js"></script>
    <script src="{% static 'assets/csrf_setup.js' %}"></script>
    <script src="{% static 'assets/update_table.js' %}"></script>
    <script src="{% static 'assets/render_data.js' %}"></script>
    <script src="{% static 'assets/save_render.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bokeh/0.12.4/bokeh.min.js"></script>
    <footer id="foot">Copyright (c) 2017 PyChart All Rights Reserved.</footer>
  </body>
</html>

pychart/pychart/templates/pychart/home.html
{% extends 'pychart/base.html' %}
{% load staticfiles %}

{% block title %}PyChart home{% endblock title %}


{% block content %}
<body style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 0%,rgba(0, 0, 0, 0.1) 100%), url({% static 'imgs/bg5.png' %})">
<div id="hp">
    <div id="hp_inner">
        <h1><img style="object-fit: cover; height: 55px;" src="{% static 'imgs/pychart_logo.png' %}"><b> PyChart</b></h1>
        <h4 id="sub_head">Beautiful Charts Made Easy!</h4>
        <p id="top_text">We love helping you make beautiful charts from complicated data. 
        <p id="top_text">With PyChart, it's simple to create poignant charts that tell a great story.</p>
    </div>
</div>
<br>
{% if chart.render %}
<div class="chart_hp col-sm-12">
    <div class="inner_chart">
        {{ chart.render | safe }}
    </div>
</div>
{% endif %}
{% endblock %}